### PR TITLE
implemented less additions to route blueprint

### PR DESCRIPTION
**Pull request by Samsinite**
Implements #1.

### CODE REVIEW

**Comment by Samsinite** [comment]
Requires publishing 0.1.0 of https://github.com/wildland/wildland-styles-generator before merging

**Comment by Samsinite** [comment]
@wildland/wildland-labs please review. After merging and deploying, please install into all wildland ember projects and start using the route generator to get work done.

Usage:

```
ember g route foo
ember g route foo/new
ember g route foo/edit
...
```

**Comment by jweakley** [comment]
We should add the usage to the README. Other than that :+1: visual.

**Comment by Samsinite** [comment]
@jweakley can you skim over that readme and give a :+1: or :-1:?

**Comment by Samsinite** [comment]
Missed adding the route blueprint code to `blueprints/route/files/__root__/__path__/__name__.js`, still need to copy over the default code here.

**Comment by jweakley** [comment]
:+1: on the readme.

**Pull request merged**
